export const UNLOCK_BOT_LIST = "UNLOCK_BOT_LIST";
export const UNLOCK_BOT_LIST_SUCCESS = "UNLOCK_BOT_LIST_SUCCESS";
export const UNLOCK_BOT_LIST_FAIL = "UNLOCK_BOT_LIST_FAIL";

export const UNLOCK_BOT = "UNLOCK_BOT";
export const UNLOCK_BOT_SUCCESS = "UNLOCK_BOT_SUCCESS";
export const UNLOCK_BOT_FAIL = "UNLOCK_BOT_FAIL";
