export const USER_SIGNUP = "USER_SIGNUP";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAIL = "USER_SIGNUP_FAIL";

export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";

export const USER_BOT_LIST = "USER_BOT_LIST";
export const USER_BOT_LIST_SUCCESS = "USER_BOT_LIST_SUCCESS";
export const USER_BOT_LIST_FAIL = "USER_BOT_LIST_FAIL";

export const GET_BOT = "GET_BOT";
export const GET_BOT_SUCCESS = "GET_BOT_SUCCESS";
export const GET_BOT_FAIL = "GET_BOT_FAIL";

// export const UNLOCK_BOT_LIST = "UNLOCK_BOT_LIST";
// export const UNLOCK_BOT_LIST_SUCCESS = "UNLOCK_BOT_LIST_SUCCESS";
// export const UNLOCK_BOT_LIST_FAIL = "UNLOCK_BOT_LIST_FAIL";

export const SEND_MESSAGE = "SEND_MESSAGE";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_FAIL = "SEND_MESSAGE_FAIL";

export const MESSAGE_HISTORY = "MESSAGE_HISTORY";
export const MESSAGE_HISTORY_SUCCESS = "MESSAGE_HISTORY_SUCCESS";
export const MESSAGE_HISTORY_FAIL = "MESSAGE_HISTORY_FAIL";

export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";
export const GET_USER_PROFILE_FAIL = "GET_USER_PROFILE_FAIL";
