export const ADMIN_LOGIN = "ADMIN_LOGIN";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_FAIL = "ADMIN_LOGIN_FAIL";
export const ADMIN_LOGOUT = "ADMIN_LOGOUT";

export const CREATE_BOT = "CREATE_BOT";
export const CREATE_BOT_SUCCESS = "CREATE_BOT_SUCCESS";
export const CREATE_BOT_FAIL = "CREATE_BOT_FAIL";

export const GET_BOT_LIST = "GET_BOT_LIST";
export const GET_BOT_LIST_SUCCESS = "GET_BOT_LIST_SUCCESS";
export const GET_BOT_LIST_FAIL = "GET_BOT_LIST_FAIL";

export const DELETE_BOT = "DELETE_BOT";
export const DELETE_BOT_SUCCESS = "DELETE_BOT_SUCCESS";
export const DELETE_BOT_FAIL = "DELETE_BOT_FAIL";

export const EDIT_BOT = "EDIT_BOT";
export const EDIT_BOT_SUCCESS = "EDIT_BOT_SUCCESS";
export const EDIT_BOT_FAIL = "EDIT_BOT_FAIL";

export const GET_BOT_DETAILS = "GET_BOT_DETAILS";
export const GET_BOT_DETAILS_SUCCESS = "GET_BOT_DETAILS_SUCCESS";
export const GET_BOT_DETAILS_FAIL = "GET_BOT_DETAILS_FAIL";

export const UPLOAD_FILE = "UPLOAD_FILE";
export const UPLOAD_FILE_SUCCESS = "UPLOAD_FILE_SUCCESS";
export const UPLOAD_FILE_FAIL = "UPLOAD_FILE_FAIL";

export const UPDATE_ROLE = "UPDATE_ROLE";
