import React from "react";

const TermsService = () => {
  return (
    <div className="termns-main h-100">
      <h2 className="text-center pt-5 m-0">Terms of Services</h2>
      <div className="rte pb-5">
        <h4>USE OF THE SERVICE</h4>
        <p>
          The Service AI Girlfriend Chat allows you to chat with AI characters.
          By using the Service, you agree that you are 18 years or older.
        </p>
        <p>
          You may only use the Service for lawful purposes and agree not to use
          it for anything illegal, fraudulent, or harmful.
        </p>
        <h4>INTELLECTUAL PROPERTY</h4>
        <p>
          All content generated by the AI and provided through the Service,
          including text, images, audio, video, and other materials, is the
          property of Infinite Labz LLC and protected by copyright and other
          laws. You may not copy, distribute, or create derivative works from
          this content.
        </p>
        <h4>USER CONTENT</h4>
        <p>
          Any content you submit through the Service must be your own original
          work. You retain ownership of any User Content you provide, but grant
          Infinite Labz LLC a license to use it in connection with operating the
          Service.
        </p>
        <p>
          You are responsible for your User Content and agree not to submit
          anything illegal, abusive, infringing, or inappropriate. Infinite Labz
          LLC reserves the right to remove any User Content without notice.
        </p>
        <h4>DISCLAIMERS</h4>
        <p>
          The Service is provided "as is" without warranty of any kind. Infinite
          Labz LLC disclaims any responsibility for the accuracy,
          appropriateness, or legality of the AI responses. Use the Service at
          your own risk.
        </p>
        <p>
          Infinite Labz LLC is not liable for any damages arising from your use
          of the Service.
        </p>
        <h4>TERMINATION</h4>
        <p>
          Infinite Labz LLC may suspend or terminate your access to the Service
          at any time for any reason. You may stop using the Service at any
          time.
        </p>
        <h4>APPLICABLE LAW</h4>
        <p>
          These Terms are governed by the laws of Delaware. Any disputes related
          to these Terms or the Service will be resolved in the courts located
          in Delaware.
        </p>
        <h4>MODIFICATIONS</h4>
        <p>
          Infinite Labz LLC may modify these Terms at any time. Your continued
          use of the Service after changes to the Terms constitutes acceptance.
        </p>
        <h4>SUPPORT</h4>
        <p>
          If you have any questions or issues, please contact support at
          support@aigirlfriendchat.net.
        </p>
        <p>
          Let me know if you would like me to add or modify anything else in
          this draft terms of service.
        </p>
      </div>
    </div>
  );
};

export default TermsService;
