export const TOTAL_CREDITS = "TOTAL_CREDITS";
export const TOTAL_CREDITS_SUCCESS = "TOTAL_CREDITS_SUCCESS";
export const TOTAL_CREDITS_FAIL = "TOTAL_CREDITS_FAIL";

export const CREDIT_LIST = "CREDIT_LIST";
export const CREDIT_LIST_SUCCESS = "CREDIT_LIST_SUCCESS";
export const CREDIT_LIST_FAIL = "CREDIT_LIST_FAIL";

export const BUY_CREDIT = "BUY_CREDIT";
export const BUY_CREDIT_SUCCESS = "BUY_CREDIT_SUCCESS";
export const BUY_CREDIT_FAIL = "BUY_CREDIT_FAIL";
